apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sentry
  namespace: sentry
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
spec:
  ingressClassName: nginx
  rules:
    - host: sentry.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sentry-web
                port:
                  number: 9000
