enabled: false

mode: deployment

replicaCount: 1

image:
  repository: otel/opentelemetry-collector-contrib

command:
  name: otelcol-contrib

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}
  processors:
    batch: {}
  exporters:
    debug:
      verbosity: normal
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]
